# Generated by Django 5.1.7 on 2025-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MileageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                ("miles_driven", models.FloatField()),
                ("duration", models.FloatField(help_text="Time taken in hours")),
                (
                    "average_speed",
                    models.FloatField(blank=True, help_text="Speed in mph", null=True),
                ),
            ],
        ),
    ]
